// <auto-generated />
using System;
using DotnetAuth.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ProjectBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251212183358_AddMovieSeed")]
    partial class AddMovieSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectBackend.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenEmpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ProjectBackend.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "Frank Darabont",
                            PosterUrl = "https://m.media-amazon.com/images/I/51NiGlapXlL.jpg",
                            Rating = 9.3000000000000007,
                            Title = "The Shawshank Redemption",
                            Year = 1994
                        },
                        new
                        {
                            Id = 2,
                            Director = "Francis Ford Coppola",
                            PosterUrl = "https://m.media-amazon.com/images/I/41+eK8zBwQL.jpg",
                            Rating = 9.1999999999999993,
                            Title = "The Godfather",
                            Year = 1972
                        },
                        new
                        {
                            Id = 3,
                            Director = "Christopher Nolan",
                            PosterUrl = "https://m.media-amazon.com/images/I/51k0qa6zH-L.jpg",
                            Rating = 9.0,
                            Title = "The Dark Knight",
                            Year = 2008
                        },
                        new
                        {
                            Id = 4,
                            Director = "Quentin Tarantino",
                            PosterUrl = "https://m.media-amazon.com/images/I/71c05lTE03L._AC_SL1024_.jpg",
                            Rating = 8.9000000000000004,
                            Title = "Pulp Fiction",
                            Year = 1994
                        },
                        new
                        {
                            Id = 5,
                            Director = "Peter Jackson",
                            PosterUrl = "https://m.media-amazon.com/images/I/51Qvs9i5a%2BL.jpg",
                            Rating = 8.9000000000000004,
                            Title = "The Lord of the Rings: The Return of the King",
                            Year = 2003
                        },
                        new
                        {
                            Id = 6,
                            Director = "Robert Zemeckis",
                            PosterUrl = "https://m.media-amazon.com/images/I/61+Kz2Rk6JL._AC_SL1000_.jpg",
                            Rating = 8.8000000000000007,
                            Title = "Forrest Gump",
                            Year = 1994
                        },
                        new
                        {
                            Id = 7,
                            Director = "David Fincher",
                            PosterUrl = "https://m.media-amazon.com/images/I/71vV1SWnSUL._AC_SL1500_.jpg",
                            Rating = 8.8000000000000007,
                            Title = "Fight Club",
                            Year = 1999
                        },
                        new
                        {
                            Id = 8,
                            Director = "Christopher Nolan",
                            PosterUrl = "https://m.media-amazon.com/images/I/51vbF7DheLL.jpg",
                            Rating = 8.6999999999999993,
                            Title = "Inception",
                            Year = 2010
                        },
                        new
                        {
                            Id = 9,
                            Director = "The Wachowskis",
                            PosterUrl = "https://m.media-amazon.com/images/I/51EG732BV3L.jpg",
                            Rating = 8.6999999999999993,
                            Title = "The Matrix",
                            Year = 1999
                        },
                        new
                        {
                            Id = 10,
                            Director = "Martin Scorsese",
                            PosterUrl = "https://m.media-amazon.com/images/I/51edC+FODKL.jpg",
                            Rating = 8.6999999999999993,
                            Title = "Goodfellas",
                            Year = 1990
                        },
                        new
                        {
                            Id = 11,
                            Director = "David Fincher",
                            PosterUrl = "https://m.media-amazon.com/images/I/71rNJQ2g-QL._AC_SL1500_.jpg",
                            Rating = 8.5999999999999996,
                            Title = "Seven",
                            Year = 1995
                        },
                        new
                        {
                            Id = 12,
                            Director = "Christopher Nolan",
                            PosterUrl = "https://m.media-amazon.com/images/I/91kFYg4fX3L._AC_SL1500_.jpg",
                            Rating = 8.5999999999999996,
                            Title = "Interstellar",
                            Year = 2014
                        },
                        new
                        {
                            Id = 13,
                            Director = "Jonathan Demme",
                            PosterUrl = "https://m.media-amazon.com/images/I/51WcRoWSQlL.jpg",
                            Rating = 8.5999999999999996,
                            Title = "The Silence of the Lambs",
                            Year = 1991
                        },
                        new
                        {
                            Id = 14,
                            Director = "Steven Spielberg",
                            PosterUrl = "https://m.media-amazon.com/images/I/51P1n0Pp-rL.jpg",
                            Rating = 8.5999999999999996,
                            Title = "Saving Private Ryan",
                            Year = 1998
                        },
                        new
                        {
                            Id = 15,
                            Director = "Fernando Meirelles",
                            PosterUrl = "https://m.media-amazon.com/images/I/51hYwc3%2BcbL.jpg",
                            Rating = 8.5999999999999996,
                            Title = "City of God",
                            Year = 2002
                        },
                        new
                        {
                            Id = 16,
                            Director = "Frank Darabont",
                            PosterUrl = "https://m.media-amazon.com/images/I/51k0qa6zH-L.jpg",
                            Rating = 8.5999999999999996,
                            Title = "The Green Mile",
                            Year = 1999
                        },
                        new
                        {
                            Id = 17,
                            Director = "Bong Joon-ho",
                            PosterUrl = "https://m.media-amazon.com/images/I/71cIkzdg86L._AC_SL1500_.jpg",
                            Rating = 8.5,
                            Title = "Parasite",
                            Year = 2019
                        },
                        new
                        {
                            Id = 18,
                            Director = "Luc Besson",
                            PosterUrl = "https://m.media-amazon.com/images/I/51Vp5cv16fL.jpg",
                            Rating = 8.5,
                            Title = "Leon: The Professional",
                            Year = 1994
                        },
                        new
                        {
                            Id = 19,
                            Director = "Ridley Scott",
                            PosterUrl = "https://m.media-amazon.com/images/I/51A7Q6Qac7L.jpg",
                            Rating = 8.5,
                            Title = "Gladiator",
                            Year = 2000
                        },
                        new
                        {
                            Id = 20,
                            Director = "Damien Chazelle",
                            PosterUrl = "https://m.media-amazon.com/images/I/81VStYnDGrL._AC_SL1500_.jpg",
                            Rating = 8.5,
                            Title = "Whiplash",
                            Year = 2014
                        },
                        new
                        {
                            Id = 21,
                            Director = "Christopher Nolan",
                            PosterUrl = "https://m.media-amazon.com/images/I/51Y-8jb8eVL.jpg",
                            Rating = 8.5,
                            Title = "The Prestige",
                            Year = 2006
                        },
                        new
                        {
                            Id = 22,
                            Director = "Martin Scorsese",
                            PosterUrl = "https://m.media-amazon.com/images/I/51U1vgbuEoL.jpg",
                            Rating = 8.5,
                            Title = "The Departed",
                            Year = 2006
                        },
                        new
                        {
                            Id = 23,
                            Director = "Roger Allers",
                            PosterUrl = "https://m.media-amazon.com/images/I/51XX-7bb2YL.jpg",
                            Rating = 8.5,
                            Title = "The Lion King",
                            Year = 1994
                        },
                        new
                        {
                            Id = 24,
                            Director = "James Cameron",
                            PosterUrl = "https://m.media-amazon.com/images/I/51FzPxPV6mL.jpg",
                            Rating = 8.5,
                            Title = "Terminator 2: Judgment Day",
                            Year = 1991
                        },
                        new
                        {
                            Id = 25,
                            Director = "Robert Zemeckis",
                            PosterUrl = "https://m.media-amazon.com/images/I/51T9V5W3uqL.jpg",
                            Rating = 8.5,
                            Title = "Back to the Future",
                            Year = 1985
                        },
                        new
                        {
                            Id = 26,
                            Director = "Ridley Scott",
                            PosterUrl = "https://m.media-amazon.com/images/I/71VmOAX-HcL._AC_SL1500_.jpg",
                            Rating = 8.5,
                            Title = "Alien",
                            Year = 1979
                        },
                        new
                        {
                            Id = 27,
                            Director = "Roman Polanski",
                            PosterUrl = "https://m.media-amazon.com/images/I/51DGiokwbrL.jpg",
                            Rating = 8.5,
                            Title = "The Pianist",
                            Year = 2002
                        },
                        new
                        {
                            Id = 28,
                            Director = "Tony Kaye",
                            PosterUrl = "https://m.media-amazon.com/images/I/51w0nggYJTL.jpg",
                            Rating = 8.5,
                            Title = "American History X",
                            Year = 1998
                        },
                        new
                        {
                            Id = 29,
                            Director = "Bryan Singer",
                            PosterUrl = "https://m.media-amazon.com/images/I/51G-5mwi0NL.jpg",
                            Rating = 8.5,
                            Title = "The Usual Suspects",
                            Year = 1995
                        },
                        new
                        {
                            Id = 30,
                            Director = "Masaki Kobayashi",
                            PosterUrl = "https://m.media-amazon.com/images/I/61tQbaO5j5L._AC_SL1000_.jpg",
                            Rating = 8.5999999999999996,
                            Title = "Harakiri",
                            Year = 1962
                        },
                        new
                        {
                            Id = 31,
                            Director = "Alfred Hitchcock",
                            PosterUrl = "https://m.media-amazon.com/images/I/51P91GZmOkL.jpg",
                            Rating = 8.5,
                            Title = "Psycho",
                            Year = 1960
                        },
                        new
                        {
                            Id = 32,
                            Director = "Todd Phillips",
                            PosterUrl = "https://m.media-amazon.com/images/I/71wIuP89A9L._AC_SL1400_.jpg",
                            Rating = 8.4000000000000004,
                            Title = "Joker",
                            Year = 2019
                        },
                        new
                        {
                            Id = 33,
                            Director = "Russo Brothers",
                            PosterUrl = "https://m.media-amazon.com/images/I/81ai6zx6eXL._AC_SL1500_.jpg",
                            Rating = 8.4000000000000004,
                            Title = "Avengers: Infinity War",
                            Year = 2018
                        },
                        new
                        {
                            Id = 34,
                            Director = "Russo Brothers",
                            PosterUrl = "https://m.media-amazon.com/images/I/81ExhpBEbHL._AC_SL1500_.jpg",
                            Rating = 8.4000000000000004,
                            Title = "Avengers: Endgame",
                            Year = 2019
                        },
                        new
                        {
                            Id = 35,
                            Director = "Mel Gibson",
                            PosterUrl = "https://m.media-amazon.com/images/I/51qCZwSUXKL.jpg",
                            Rating = 8.3000000000000007,
                            Title = "Braveheart",
                            Year = 1995
                        },
                        new
                        {
                            Id = 36,
                            Director = "Martin Scorsese",
                            PosterUrl = "https://m.media-amazon.com/images/I/91K8M8XlC0L._AC_SL1500_.jpg",
                            Rating = 8.1999999999999993,
                            Title = "The Wolf of Wall Street",
                            Year = 2013
                        },
                        new
                        {
                            Id = 37,
                            Director = "Quentin Tarantino",
                            PosterUrl = "https://m.media-amazon.com/images/I/81trWMMqEDL._AC_SL1500_.jpg",
                            Rating = 8.4000000000000004,
                            Title = "Django Unchained",
                            Year = 2012
                        },
                        new
                        {
                            Id = 38,
                            Director = "Quentin Tarantino",
                            PosterUrl = "https://m.media-amazon.com/images/I/91lWvLmX48L._AC_SL1500_.jpg",
                            Rating = 8.3000000000000007,
                            Title = "Inglourious Basterds",
                            Year = 2009
                        },
                        new
                        {
                            Id = 39,
                            Director = "Denis Villeneuve",
                            PosterUrl = "https://m.media-amazon.com/images/I/71mazqZu%2BtL._AC_SL1500_.jpg",
                            Rating = 8.0,
                            Title = "Blade Runner 2049",
                            Year = 2017
                        },
                        new
                        {
                            Id = 40,
                            Director = "David Fincher",
                            PosterUrl = "https://m.media-amazon.com/images/I/71mUet6xxuL._AC_SL1500_.jpg",
                            Rating = 7.7999999999999998,
                            Title = "The Social Network",
                            Year = 2010
                        },
                        new
                        {
                            Id = 41,
                            Director = "Alejandro G. Iñárritu",
                            PosterUrl = "https://m.media-amazon.com/images/I/81zMqrVwYpL._AC_SL1500_.jpg",
                            Rating = 8.0,
                            Title = "The Revenant",
                            Year = 2015
                        },
                        new
                        {
                            Id = 42,
                            Director = "Ron Howard",
                            PosterUrl = "https://m.media-amazon.com/images/I/61DM9Rr1t5L._AC_SL1000_.jpg",
                            Rating = 8.1999999999999993,
                            Title = "A Beautiful Mind",
                            Year = 2001
                        },
                        new
                        {
                            Id = 43,
                            Director = "Martin Scorsese",
                            PosterUrl = "https://m.media-amazon.com/images/I/81v%2B-FcVGlL._AC_SL1500_.jpg",
                            Rating = 8.1999999999999993,
                            Title = "Shutter Island",
                            Year = 2010
                        },
                        new
                        {
                            Id = 44,
                            Director = "Christopher Nolan",
                            PosterUrl = "https://m.media-amazon.com/images/I/81sDWcoH6tL._AC_SL1500_.jpg",
                            Rating = 8.4000000000000004,
                            Title = "The Dark Knight Rises",
                            Year = 2012
                        },
                        new
                        {
                            Id = 45,
                            Director = "James Mangold",
                            PosterUrl = "https://m.media-amazon.com/images/I/91wxPvYBn6L._AC_SL1500_.jpg",
                            Rating = 8.0999999999999996,
                            Title = "Logan",
                            Year = 2017
                        },
                        new
                        {
                            Id = 46,
                            Director = "George Miller",
                            PosterUrl = "https://m.media-amazon.com/images/I/91oGtaqmO0L._AC_SL1500_.jpg",
                            Rating = 8.0999999999999996,
                            Title = "Mad Max: Fury Road",
                            Year = 2015
                        },
                        new
                        {
                            Id = 47,
                            Director = "Peter Weir",
                            PosterUrl = "https://m.media-amazon.com/images/I/51K219VKHSL.jpg",
                            Rating = 8.1999999999999993,
                            Title = "The Truman Show",
                            Year = 1998
                        },
                        new
                        {
                            Id = 48,
                            Director = "David Fincher",
                            PosterUrl = "https://m.media-amazon.com/images/I/71mUet6xxuL._AC_SL1500_.jpg",
                            Rating = 7.7999999999999998,
                            Title = "The Social Network",
                            Year = 2010
                        },
                        new
                        {
                            Id = 49,
                            Director = "Alejandro G. Iñárritu",
                            PosterUrl = "https://m.media-amazon.com/images/I/81zMqrVwYpL._AC_SL1500_.jpg",
                            Rating = 8.0,
                            Title = "The Revenant",
                            Year = 2015
                        },
                        new
                        {
                            Id = 50,
                            Director = "Ron Howard",
                            PosterUrl = "https://m.media-amazon.com/images/I/61DM9Rr1t5L._AC_SL1000_.jpg",
                            Rating = 8.1999999999999993,
                            Title = "A Beautiful Mind",
                            Year = 2001
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProjectBackend.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProjectBackend.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectBackend.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProjectBackend.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
