// <auto-generated />
using System;
using DotnetAuth.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ProjectBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251220145222_UpdatePosters")]
    partial class UpdatePosters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectBackend.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenEmpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ProjectBackend.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "Frank Darabont",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
                            Rating = 9.3000000000000007,
                            Title = "The Shawshank Redemption",
                            Year = 1994
                        },
                        new
                        {
                            Id = 2,
                            Director = "Francis Ford Coppola",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
                            Rating = 9.1999999999999993,
                            Title = "The Godfather",
                            Year = 1972
                        },
                        new
                        {
                            Id = 3,
                            Director = "Christopher Nolan",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
                            Rating = 9.0,
                            Title = "The Dark Knight",
                            Year = 2008
                        },
                        new
                        {
                            Id = 4,
                            Director = "Quentin Tarantino",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/fIE3lAGcZDV1G6XM5KmuWnNsPp1.jpg",
                            Rating = 8.9000000000000004,
                            Title = "Pulp Fiction",
                            Year = 1994
                        },
                        new
                        {
                            Id = 5,
                            Director = "Peter Jackson",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
                            Rating = 8.9000000000000004,
                            Title = "The Lord of the Rings: The Return of the King",
                            Year = 2003
                        },
                        new
                        {
                            Id = 6,
                            Director = "Robert Zemeckis",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg",
                            Rating = 8.8000000000000007,
                            Title = "Forrest Gump",
                            Year = 1994
                        },
                        new
                        {
                            Id = 7,
                            Director = "David Fincher",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg",
                            Rating = 8.8000000000000007,
                            Title = "Fight Club",
                            Year = 1999
                        },
                        new
                        {
                            Id = 8,
                            Director = "Christopher Nolan",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
                            Rating = 8.6999999999999993,
                            Title = "Inception",
                            Year = 2010
                        },
                        new
                        {
                            Id = 9,
                            Director = "The Wachowskis",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
                            Rating = 8.6999999999999993,
                            Title = "The Matrix",
                            Year = 1999
                        },
                        new
                        {
                            Id = 10,
                            Director = "Martin Scorsese",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
                            Rating = 8.6999999999999993,
                            Title = "Goodfellas",
                            Year = 1990
                        },
                        new
                        {
                            Id = 11,
                            Director = "David Fincher",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg",
                            Rating = 8.5999999999999996,
                            Title = "Se7en",
                            Year = 1995
                        },
                        new
                        {
                            Id = 12,
                            Director = "Christopher Nolan",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
                            Rating = 8.5999999999999996,
                            Title = "Interstellar",
                            Year = 2014
                        },
                        new
                        {
                            Id = 13,
                            Director = "Jonathan Demme",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
                            Rating = 8.5999999999999996,
                            Title = "The Silence of the Lambs",
                            Year = 1991
                        },
                        new
                        {
                            Id = 14,
                            Director = "Steven Spielberg",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/uqx37cS8cpHg8U35f9U5IBlrCV3.jpg",
                            Rating = 8.5999999999999996,
                            Title = "Saving Private Ryan",
                            Year = 1998
                        },
                        new
                        {
                            Id = 15,
                            Director = "Fernando Meirelles",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/k7eYdWvhYQyRQoU2TB2A2Xu2TfD.jpg",
                            Rating = 8.5999999999999996,
                            Title = "City of God",
                            Year = 2002
                        },
                        new
                        {
                            Id = 16,
                            Director = "Frank Darabont",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/o0lO84GI7qrG6XFvtsPOSV7CTNa.jpg",
                            Rating = 8.5999999999999996,
                            Title = "The Green Mile",
                            Year = 1999
                        },
                        new
                        {
                            Id = 17,
                            Director = "Bong Joon-ho",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
                            Rating = 8.5,
                            Title = "Parasite",
                            Year = 2019
                        },
                        new
                        {
                            Id = 18,
                            Director = "Luc Besson",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/yI6X2cCM5YPJtxMhUd3dPGqDAhw.jpg",
                            Rating = 8.5,
                            Title = "Léon: The Professional",
                            Year = 1994
                        },
                        new
                        {
                            Id = 19,
                            Director = "Ridley Scott",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
                            Rating = 8.5,
                            Title = "Gladiator",
                            Year = 2000
                        },
                        new
                        {
                            Id = 20,
                            Director = "Damien Chazelle",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/6uSPcdGJAkF6P5kP1K9z5i2nV8p.jpg",
                            Rating = 8.5,
                            Title = "Whiplash",
                            Year = 2014
                        },
                        new
                        {
                            Id = 21,
                            Director = "Christopher Nolan",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/5MXyQfz8xUP3dIFPTubhTsbFY6N.jpg",
                            Rating = 8.5,
                            Title = "The Prestige",
                            Year = 2006
                        },
                        new
                        {
                            Id = 22,
                            Director = "Martin Scorsese",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/nT97ifVT2J1yMQmeq20Qblg61T.jpg",
                            Rating = 8.5,
                            Title = "The Departed",
                            Year = 2006
                        },
                        new
                        {
                            Id = 23,
                            Director = "Roger Allers",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
                            Rating = 8.5,
                            Title = "The Lion King",
                            Year = 1994
                        },
                        new
                        {
                            Id = 24,
                            Director = "James Cameron",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/5M0j0B18abtBI5gi2RhfjjurTqb.jpg",
                            Rating = 8.5,
                            Title = "Terminator 2: Judgment Day",
                            Year = 1991
                        },
                        new
                        {
                            Id = 25,
                            Director = "Robert Zemeckis",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/pTpxQB1N0waaSc3OSn0e9oc8kx9.jpg",
                            Rating = 8.5,
                            Title = "Back to the Future",
                            Year = 1985
                        },
                        new
                        {
                            Id = 26,
                            Director = "Ridley Scott",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg",
                            Rating = 8.5,
                            Title = "Alien",
                            Year = 1979
                        },
                        new
                        {
                            Id = 27,
                            Director = "Roman Polanski",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg",
                            Rating = 8.5,
                            Title = "The Pianist",
                            Year = 2002
                        },
                        new
                        {
                            Id = 28,
                            Director = "Tony Kaye",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/c2gsmSQ2Cqv8zosqKOCwRS0GFBS.jpg",
                            Rating = 8.5,
                            Title = "American History X",
                            Year = 1998
                        },
                        new
                        {
                            Id = 29,
                            Director = "Bryan Singer",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/bUPmtQzrRhzqYySeiMpv7GurAfm.jpg",
                            Rating = 8.5,
                            Title = "The Usual Suspects",
                            Year = 1995
                        },
                        new
                        {
                            Id = 30,
                            Director = "Masaki Kobayashi",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/5konZnIbcAxZjP616Cz5o9bKEfW.jpg",
                            Rating = 8.5999999999999996,
                            Title = "Harakiri",
                            Year = 1962
                        },
                        new
                        {
                            Id = 31,
                            Director = "Alfred Hitchcock",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/81d8oyEFgj7FlxJqSDXWr8JH8kV.jpg",
                            Rating = 8.5,
                            Title = "Psycho",
                            Year = 1960
                        },
                        new
                        {
                            Id = 32,
                            Director = "Todd Phillips",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
                            Rating = 8.4000000000000004,
                            Title = "Joker",
                            Year = 2019
                        },
                        new
                        {
                            Id = 33,
                            Director = "Russo Brothers",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
                            Rating = 8.4000000000000004,
                            Title = "Avengers: Infinity War",
                            Year = 2018
                        },
                        new
                        {
                            Id = 34,
                            Director = "Russo Brothers",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
                            Rating = 8.4000000000000004,
                            Title = "Avengers: Endgame",
                            Year = 2019
                        },
                        new
                        {
                            Id = 35,
                            Director = "Mel Gibson",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/or1gBugydmjToAEq7OZY0owwFk.jpg",
                            Rating = 8.3000000000000007,
                            Title = "Braveheart",
                            Year = 1995
                        },
                        new
                        {
                            Id = 36,
                            Director = "Martin Scorsese",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/pWHf4khOloNVfCxscsXFj3jj6gP.jpg",
                            Rating = 8.1999999999999993,
                            Title = "The Wolf of Wall Street",
                            Year = 2013
                        },
                        new
                        {
                            Id = 37,
                            Director = "Quentin Tarantino",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg",
                            Rating = 8.4000000000000004,
                            Title = "Django Unchained",
                            Year = 2012
                        },
                        new
                        {
                            Id = 38,
                            Director = "Quentin Tarantino",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg",
                            Rating = 8.3000000000000007,
                            Title = "Inglourious Basterds",
                            Year = 2009
                        },
                        new
                        {
                            Id = 39,
                            Director = "Denis Villeneuve",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
                            Rating = 8.0,
                            Title = "Blade Runner 2049",
                            Year = 2017
                        },
                        new
                        {
                            Id = 40,
                            Director = "David Fincher",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
                            Rating = 7.7999999999999998,
                            Title = "The Social Network",
                            Year = 2010
                        },
                        new
                        {
                            Id = 41,
                            Director = "Alejandro G. Iñárritu",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/oXUWEc5i3wYyFnL1Ycu8ppxxPvs.jpg",
                            Rating = 8.0,
                            Title = "The Revenant",
                            Year = 2015
                        },
                        new
                        {
                            Id = 42,
                            Director = "Ron Howard",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/zwzWCmH72OSC9NA0ipoqw5Zjya8.jpg",
                            Rating = 8.1999999999999993,
                            Title = "A Beautiful Mind",
                            Year = 2001
                        },
                        new
                        {
                            Id = 43,
                            Director = "Martin Scorsese",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/kve20tXwUZpu4GUX8l6X7Z4jmL6.jpg",
                            Rating = 8.1999999999999993,
                            Title = "Shutter Island",
                            Year = 2010
                        },
                        new
                        {
                            Id = 44,
                            Director = "Christopher Nolan",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg",
                            Rating = 8.4000000000000004,
                            Title = "The Dark Knight Rises",
                            Year = 2012
                        },
                        new
                        {
                            Id = 45,
                            Director = "James Mangold",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg",
                            Rating = 8.0999999999999996,
                            Title = "Logan",
                            Year = 2017
                        },
                        new
                        {
                            Id = 46,
                            Director = "George Miller",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
                            Rating = 8.0999999999999996,
                            Title = "Mad Max: Fury Road",
                            Year = 2015
                        },
                        new
                        {
                            Id = 47,
                            Director = "Peter Weir",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/vt1u0lHk3O2Yp6u7p9p6ZxQ5ZbM.jpg",
                            Rating = 8.1999999999999993,
                            Title = "The Truman Show",
                            Year = 1998
                        },
                        new
                        {
                            Id = 48,
                            Director = "Coen Brothers",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/5DxkT6yWEYyFjPZtxe2F0KxL5T4.jpg",
                            Rating = 8.0999999999999996,
                            Title = "The Big Lebowski",
                            Year = 1998
                        },
                        new
                        {
                            Id = 49,
                            Director = "Coen Brothers",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/6o0fQX0uTzE3C8f6TRf0wK6n6Qx.jpg",
                            Rating = 8.0999999999999996,
                            Title = "No Country for Old Men",
                            Year = 2007
                        },
                        new
                        {
                            Id = 50,
                            Director = "Paul Thomas Anderson",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/fa0RDkAlCec0STeMNAhPaF89q6C.jpg",
                            Rating = 8.1999999999999993,
                            Title = "There Will Be Blood",
                            Year = 2007
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProjectBackend.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProjectBackend.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectBackend.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProjectBackend.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
